import { useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Clock3, FileText, Search, X } from 'lucide-react'

const invoices = [
  { id: 'INV-26091', student: 'Nguyễn Minh Anh', batch: 'ĐGNL 12A · K24', issued: '12/06/2026', status: 'Đã thanh toán', total: 2990000, items: [{ name: 'Học phí Luyện thi ĐGNL toàn diện', amount: 2900000 }, { name: 'Tài liệu học tập', amount: 90000 }], history: [{ time: '12/06/2026 · 09:12', text: 'Hóa đơn được phát hành', type: 'created' }, { time: '12/06/2026 · 09:26', text: 'Thanh toán chuyển khoản thành công', type: 'paid' }] },
  { id: 'INV-26126', student: 'Trần Hoàng Long', batch: 'ĐGNL 12B · K24', issued: '18/06/2026', status: 'Thanh toán một phần', total: 2990000, items: [{ name: 'Học phí Luyện thi ĐGNL toàn diện · Đợt 2', amount: 1490000 }, { name: 'Phí kiểm tra đầu vào', amount: 50000 }], history: [{ time: '18/06/2026 · 14:30', text: 'Hóa đơn được phát hành', type: 'created' }, { time: '20/06/2026 · 08:40', text: 'Đã nhận 1.500.000đ', type: 'partial' }, { time: '09/09/2026 · 10:00', text: 'Đã gửi nhắc thanh toán', type: 'notice' }] },
  { id: 'INV-25984', student: 'Lê Thị Mai', batch: 'ĐGNL 11A · K25', issued: '03/05/2026', status: 'Chờ thanh toán', total: 2490000, items: [{ name: 'Học phí Nền tảng ĐGNL lớp 11', amount: 2400000 }, { name: 'Tài liệu học tập', amount: 90000 }], history: [{ time: '03/05/2026 · 11:05', text: 'Hóa đơn được phát hành', type: 'created' }, { time: '05/05/2026 · 08:00', text: 'Email hóa đơn đã được gửi', type: 'notice' }] },
  { id: 'INV-26152', student: 'Phạm Gia Huy', batch: 'ĐGNL 12A · K24', issued: '24/06/2026', status: 'Quá hạn', total: 2990000, items: [{ name: 'Học phí Luyện thi ĐGNL toàn diện', amount: 2990000 }], history: [{ time: '24/06/2026 · 16:10', text: 'Hóa đơn được phát hành', type: 'created' }, { time: '01/09/2026 · 00:01', text: 'Hóa đơn chuyển sang trạng thái quá hạn', type: 'overdue' }, { time: '08/09/2026 · 09:00', text: 'Đã gửi nhắc thanh toán lần 2', type: 'notice' }] },
]
const statuses = ['Đã thanh toán', 'Thanh toán một phần', 'Chờ thanh toán', 'Quá hạn']
const formatMoney = (amount) => `${new Intl.NumberFormat('vi-VN').format(amount)}đ`

function InvoiceStatus({ status }) { return <span className={`hl-invoice-status ${status === 'Đã thanh toán' ? 'paid' : status === 'Quá hạn' ? 'overdue' : status === 'Thanh toán một phần' ? 'partial' : 'pending'}`}>{status}</span> }

function InvoiceManagement() {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('Tất cả')
  const [selected, setSelected] = useState(null)
  const list = useMemo(() => invoices.filter((item) => (filter === 'Tất cả' || item.status === filter) && `${item.id} ${item.student} ${item.batch}`.toLowerCase().includes(query.toLowerCase())), [query, filter])
  return <><div className="hl-staff-title"><div><span className="hl-staff-date">SF-12 · INVOICE MANAGEMENT</span><h1>Quản lý hóa đơn</h1><p>Tra cứu hóa đơn, khoản mục thanh toán và lịch sử xử lý.</p></div></div><section className="hl-staff-panel hl-invoice-panel"><div className="hl-invoice-filters"><label><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã hóa đơn, học viên..." /></label><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>Tất cả</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><span>{list.length} hóa đơn</span></div><div className="hl-invoice-table"><div className="hl-invoice-row head"><span>Mã hóa đơn</span><span>Học viên / batch</span><span>Ngày phát hành</span><span>Tổng tiền</span><span>Trạng thái</span><span /></div>{list.map((invoice) => <button className="hl-invoice-row" type="button" key={invoice.id} onClick={() => setSelected(invoice)}><span className="hl-invoice-id"><FileText size={17} /><b>{invoice.id}</b></span><span><b>{invoice.student}</b><small>{invoice.batch}</small></span><span>{invoice.issued}</span><strong>{formatMoney(invoice.total)}</strong><InvoiceStatus status={invoice.status} /><span className="hl-invoice-view">Xem chi tiết</span></button>)}{!list.length && <div className="hl-staff-empty">Không tìm thấy hóa đơn phù hợp.</div>}</div></section>{selected && <div className="hl-staff-modal-backdrop"><section className="hl-staff-modal hl-invoice-modal"><button type="button" className="hl-staff-modal-close" onClick={() => setSelected(null)}><X size={19} /></button><div className="hl-invoice-modal-heading"><div><span className="hl-staff-eyebrow">CHI TIẾT HÓA ĐƠN</span><h2>{selected.id}</h2><p>{selected.student} · {selected.batch}</p></div><InvoiceStatus status={selected.status} /></div><div className="hl-invoice-meta"><span><CalendarDays size={15} />Phát hành: {selected.issued}</span><span><FileText size={15} />{selected.items.length} khoản mục</span></div><section className="hl-invoice-items"><h3>Khoản mục</h3>{selected.items.map((item) => <div key={item.name}><span>{item.name}</span><strong>{formatMoney(item.amount)}</strong></div>)}<div className="total"><b>Tổng thanh toán</b><strong>{formatMoney(selected.total)}</strong></div></section><section className="hl-invoice-history"><h3><Clock3 size={16} />Lịch sử hóa đơn</h3>{selected.history.map((entry) => <div key={entry.time}><i className={entry.type} /><span><b>{entry.text}</b><small>{entry.time}</small></span></div>)}</section></section></div>}</>
}

export default InvoiceManagement
