import { useMemo, useState } from 'react'
import { CheckCircle2, CreditCard, Landmark, Search, Smartphone, X } from 'lucide-react'

const payments = [
  { id: 'PAY-260912-001', invoice: 'INV-26091', student: 'Nguyễn Minh Anh', amount: 2990000, method: 'Chuyển khoản ngân hàng', time: '12/06/2026 · 09:26', status: 'Thành công', reference: 'MB-124989320', note: 'Thanh toán học phí đầy đủ.' },
  { id: 'PAY-260620-014', invoice: 'INV-26126', student: 'Trần Hoàng Long', amount: 1500000, method: 'Ví MoMo', time: '20/06/2026 · 08:40', status: 'Thành công', reference: 'MOMO-7D8K3A2', note: 'Thanh toán đợt 1.' },
  { id: 'PAY-260905-031', invoice: 'INV-25984', student: 'Lê Thị Mai', amount: 2490000, method: 'Thẻ quốc tế', time: '05/09/2026 · 16:13', status: 'Thất bại', reference: 'VNP-0G9QW76', note: 'Ngân hàng từ chối giao dịch.' },
  { id: 'PAY-260909-022', invoice: 'INV-26152', student: 'Phạm Gia Huy', amount: 2990000, method: 'Chuyển khoản ngân hàng', time: '09/09/2026 · 11:05', status: 'Đang chờ', reference: 'MB-124994701', note: 'Đang chờ đối soát giao dịch.' },
  { id: 'PAY-260824-008', invoice: 'INV-25877', student: 'Võ Thanh Hà', amount: 500000, method: 'Ví MoMo', time: '24/08/2026 · 14:20', status: 'Đã hoàn tiền', reference: 'MOMO-4XJ0PL8', note: 'Hoàn tiền phần học phí điều chỉnh.' },
]
const statuses = ['Thành công', 'Thất bại', 'Đang chờ', 'Đã hoàn tiền']
const money = (amount) => `${new Intl.NumberFormat('vi-VN').format(amount)}đ`
const methodIcon = (method) => method.includes('MoMo') ? Smartphone : method.includes('ngân hàng') ? Landmark : CreditCard
function PaymentStatus({ status }) { return <span className={`hl-payment-status ${status === 'Thành công' ? 'success' : status === 'Thất bại' ? 'failed' : status === 'Đã hoàn tiền' ? 'refunded' : 'pending'}`}>{status}</span> }

function PaymentManagement() {
  const [filter, setFilter] = useState('Tất cả')
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState(null)
  const list = useMemo(() => payments.filter((item) => (filter === 'Tất cả' || item.status === filter) && `${item.id} ${item.student} ${item.invoice}`.toLowerCase().includes(query.toLowerCase())), [filter, query])
  const summary = statuses.reduce((result, status) => ({ ...result, [status]: payments.filter((item) => item.status === status).length }), {})
  return <><div className="hl-staff-title"><div><span className="hl-staff-date">SF-13 · PAYMENT MANAGEMENT</span><h1>Quản lý thanh toán</h1><p>Theo dõi và đối soát các giao dịch tài chính của học viên.</p></div></div><section className="hl-staff-panel hl-payment-panel"><div className="hl-payment-summary">{statuses.map((status) => <span className={status === 'Thành công' ? 'success' : status === 'Thất bại' ? 'failed' : status === 'Đã hoàn tiền' ? 'refunded' : 'pending'} key={status}><b>{summary[status]}</b>{status}</span>)}</div><div className="hl-payment-filters"><label><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã giao dịch, học viên, hóa đơn..." /></label><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>Tất cả</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><span>{list.length} giao dịch</span></div><div className="hl-payment-table"><div className="hl-payment-row head"><span>Mã giao dịch</span><span>Học viên / hóa đơn</span><span>Phương thức</span><span>Thời gian</span><span>Số tiền</span><span>Trạng thái</span></div>{list.map((payment) => { const Icon = methodIcon(payment.method); return <button className="hl-payment-row" type="button" key={payment.id} onClick={() => setSelected(payment)}><span><b>{payment.id}</b><small>{payment.reference}</small></span><span><b>{payment.student}</b><small>{payment.invoice}</small></span><span className="hl-payment-method"><Icon size={16} />{payment.method}</span><span>{payment.time}</span><strong>{money(payment.amount)}</strong><PaymentStatus status={payment.status} /></button> })}{!list.length && <div className="hl-staff-empty">Không có giao dịch phù hợp.</div>}</div></section>{selected && <div className="hl-staff-modal-backdrop"><section className="hl-staff-modal hl-payment-modal"><button type="button" className="hl-staff-modal-close" onClick={() => setSelected(null)}><X size={19} /></button><div className="hl-payment-modal-heading"><div><span className="hl-staff-eyebrow">CHI TIẾT GIAO DỊCH</span><h2>{selected.id}</h2><p>Mã tham chiếu: {selected.reference}</p></div><PaymentStatus status={selected.status} /></div><div className="hl-payment-amount"><span>TỔNG GIAO DỊCH</span><strong>{money(selected.amount)}</strong></div><div className="hl-payment-details"><div><small>Học viên</small><b>{selected.student}</b></div><div><small>Hóa đơn liên quan</small><b>{selected.invoice}</b></div><div><small>Phương thức</small><b>{selected.method}</b></div><div><small>Thời gian giao dịch</small><b>{selected.time}</b></div></div><div className="hl-payment-note"><small>GHI CHÚ</small><p>{selected.note}</p></div></section></div>}</>
}

export default PaymentManagement
